### PR TITLE
Dockerize CONcrescent

### PR DESCRIPTION
**Pull request by Wolvan**
This PR includes everything necessary to run CONcrescent 2 and 3 in a dockerized environment, which brings benefits such as easy spinup/spindown of CONcrescent instances, combining it with external docker setups like [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) and [acme-companion](https://github.com/nginx-proxy/acme-companion) for easy SSL encryption as well as stable, clear cut execution environments.

### CODE REVIEW

**Comment by Tsaukpaetra** [comment]
Oh sweet! I was somehow never notified about this (perhaps my Github settings are borked). I'll try to look into this.
CM2 has essentially ceased development, but I'll still probably check everything over, there's a lot of... issues I never did get fixed.

**Comment by Wolvan** [comment]
Actually, I probably should clean this branch up.
I ended up making a lot of fixes and changes to CM2 as I/Snowpity, Inc. is actively using it for Mare Fair and we found a couple things that didn't work or were missing from the features we needed.
I did start dockerizing CM3 as well, but at the time it wasn't really in a state where I could get much running.

Should I open a new PR or just clean this one here up? Should I put CM3 dockerization in as well?

**Comment by Tsaukpaetra** [comment]
🤔 if you could split the updates so one is for CM2 and the other for CM3 I
think that would be good, at one point I was going to convert the svn
layout into branches but haven't got there yet.

**Comment by Wolvan** [comment]
Replaced by #10

**Pull request closed without merging**
